version: "3"

services:
  occupation-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
      - ./package-lock.json:/app/package-lock.json:ro
      - ./package.json:/app/package.json:ro
      - ./unavailable_days.json:/app/unavailable_days.json


