version: "3"

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - 9191:9191
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
    - occupation-crawler
  occupation-crawler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 8080:8080
    volumes:
      - ./dist:/app/dist
      - ./src:/app/src
      - ./package-lock.json:/app/package-lock.json:ro
      - ./package.json:/app/package.json:ro
      - ./unavailable_days.json:/app/unavailable_days.json
